[package]
name = "merge_ksorted_arrays"
version = "0.1.0"
authors = ["Ratul Buragohain <ratul75@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heap = {path ="../heap"}
